# Generated by Django 3.1.6 on 2021-02-04 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Method')),
                ('taxPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Tax price')),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Shipping price')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Total price')),
                ('isPaid', models.BooleanField(default=False, verbose_name='Is paid?')),
                ('paidAt', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('isDelivered', models.BooleanField(default=False, verbose_name='Is delivered?')),
                ('deliveredAt', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('postalCode', models.IntegerField(blank=True, default=0, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country')),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Price')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Price')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
        ),
    ]
